### ISSUE TITLE
Layout broken under Angular 10

### ISSUE THREAD

**Issue by heldiX** [beeman/ngx-tui#1]
Hallo beeman,

first thank you very much for this project!

I tried to use this in a brand new angular 10 project as u described in the manual. But the layout ist broken heavily:

![Unbenannt](https://user-images.githubusercontent.com/22490966/86526308-d2d68c00-be92-11ea-95b2-e6f756bb95d6.png)

Greetings from germany,
heldiX

**Comment by beeman** [comment]
Hi there @heldiX, thanks for reporting the issue!

This does not look good. It looks like the styles are not loading properly.

Could you add this to your style.(s)css to see if that improves it?

```scss
@import '~@toast-ui/editor/dist/toastui-editor.css';
```

**Comment by heldiX** [comment]
Ok looks pretty well now! Is working at least in WYSIWYG mode. Markdown mode is still a bit buggy to me:
![demo](https://user-images.githubusercontent.com/22490966/86526864-6d39ce00-be99-11ea-8e67-c0bc8498f69e.gif)

**Comment by beeman** [comment]
Thanks for the visual! I'm planning to implement and use the editor tomorrow in one of my own projects so I'll see how it works for me.

Do you have any other styles in your app?

**Comment by heldiX** [comment]
No i dont. I created a new ang10 project and didnt really do anything besides the importing in app.module and declaration in the html.

**Comment by beeman** [comment]
Hey @heldiX  - I just published version 2.0.0 that does not include any styles, it leaves it up the user to import it.

Also, I created [a sandbox](https://github.com/beeman/ngx-tui-sandbox) with the editor installed, can you see if this works as expected?

**Comment by Aleksandr-ru** [comment]
Same here in angular 9.
Adding styles to app global `style.scss` solves the problem.
It would be nice make it works without manual adding app global styles

**Comment by Aleksandr-ru** [comment]
BTW without adding optional styles
```
/** optional */
@import '~codemirror/lib/codemirror.css';
@import '~highlight.js/styles/github.css';
```
layout still broken in markdown mode
